### PR TITLE
allow other list of packages to be solved

### PR DESCRIPTION
**Pull request by harshad16**
allow other list of packages to be solved
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

## Related Issues and Dependencies

Related-to: https://github.com/thoth-station/thoth-application/issues/1764

Copied from 
https://raw.githubusercontent.com/fridex/devnull/master/rhods_nb_packages.txt
https://raw.githubusercontent.com/fridex/devnull/master/ray_pkgs.txt
credit-to: @fridex

### CODE REVIEW

**Review by fridex — COMMENTED** [review]
Thanks for working on this, but I'm not sure about this change. Can we keep just a list of packages that the system is supposed to be initialized with?

**Comment by fridex** [comment]
> Thanks for working on this, but I'm not sure about this change. Can we keep just a list of packages that the system is supposed to be initialized with?

See this comment and discussion https://github.com/thoth-station/thoth-application/issues/1763#issuecomment-870345028

**Comment by harshad16** [comment]
> Thanks for working on this, but I'm not sure about this change. Can we keep just a list of packages that the system is supposed to be initialized with?

yes, @fridex 
we would separate that on the deployment side
For this pr, the goal, is to have all this list available in init-job for future.
if there is to be thoth deployment in the rhods cluster, then this would be beneficial was my thought.

**Comment by fridex** [comment]
> > Thanks for working on this, but I'm not sure about this change. Can we keep just a list of packages that the system is supposed to be initialized with?
> 
> yes, @fridex
> we would separate that on the deployment side
> For this pr, the goal, is to have all this list available in init-job for future.
> if there is to be thoth deployment in the rhods cluster, then this would be beneficial was my thought.

I'm not sure if this is something we want to maintain and support. My point is how the system is initialized - the initialization should be agnostic to any consumer. In other words, it is ok if we maintain a list of packages that should be used for initialization, the fact they are RHODS/Ray specific is a detail that should not go to sources or deployment templates. From Thoth point of view, it should be just "initialize the system with the given set of packages".

**Comment by harshad16** [comment]
> I'm not sure if this is something we want to maintain and support. My point is how the system is initialized - the initialization should be agnostic to any consumer. In other words, it is ok if we maintain a list of packages that should be used for initialization, the fact they are RHODS/Ray specific is a detail that should not go to sources or deployment templates. From Thoth point of view, it should be just "initialize the system with the given set of packages".

very valid point. initialization should be agnostic of customer
thanks for the comment.

**Pull request closed without merging**
