### PR TITLE
port to python 38

### PR DESCRIPTION
**Pull request by bissenbay**
Related-To: https://github.com/thoth-station/thoth-application/issues/545

### CODE REVIEW

**Comment by bissenbay** [comment]
@fridex @harshad16 We don't have `.aicoe-ci.yaml` file in this repo, is it expected?

**Comment by harshad16** [comment]
can you please include the `.aicoe-ci.yaml`
```
check:
  - thoth-build
  - thoth-precommit
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
  build-stratergy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: init-job
  registry-secret: thoth-station-thoth-pusher-secret
deploy:
  project-org: "thoth-station"
  project-name: "thoth-application"
  image-name: "init-job"
  overlay-contextpath: "init-job/overlays/test/imagestreamtag.yaml"
```

**Comment by bissenbay** [comment]
> can you please include the `.aicoe-ci.yaml`
> 
> ```
> check:
>   - thoth-build
>   - thoth-precommit
> build:
>   base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
>   build-stratergy: Source
>   registry: quay.io
>   registry-org: thoth-station
>   registry-project: init-job
>   registry-secret: thoth-station-thoth-pusher-secret
> deploy:
>   project-org: "thoth-station"
>   project-name: "thoth-application"
>   image-name: "init-job"
>   overlay-contextpath: "init-job/overlays/test/imagestreamtag.yaml"
> ```

thanks @harshad16 , https://github.com/thoth-station/init-job/pull/409/commits/5ba21aca7ba657ede79e7d92aab5b4a42bfd55ca

**Comment by bissenbay** [comment]
@harshad16 changed here as well

**Review by harshad16 — APPROVED** [review]
lgtm, thanks :100:

**Pull request merged**
