### PR TITLE
redundant use of IMAGE_STREAM_TAG

### PR DESCRIPTION
**Pull request by bissenbay**

### CODE REVIEW

**Comment by fridex** [comment]
@harshad16 do we want to keep it or should it be discarded?

**Comment by harshad16** [comment]
@bissenbay  @fridex  sorry for missing this PR. 
I would suggest keeping the Tag, and using it in here https://github.com/thoth-station/init-job/blob/67546dc7c0d482725e87b0d8c505f5c84c786455/openshift/job-template.yaml#L41
with us moving to ci/cd tools for managing image and deployment, maybe having custom tag would help.

**Comment by bissenbay** [comment]
> @bissenbay @fridex sorry for missing this PR.
> I would suggest keeping the Tag, and using it in here
> 
> https://github.com/thoth-station/init-job/blob/67546dc7c0d482725e87b0d8c505f5c84c786455/openshift/job-template.yaml#L41
> 
> 
> with us moving to ci/cd tools for managing image and deployment, maybe having custom tag would help.

@fridex @harshad16 I did the change you asked. But, the thing I say redundant is `IMAGE_STREAM_TAG` parameter is written twice that's why I'm deleting one of them. The first is  [1](https://github.com/thoth-station/init-job/blob/master/openshift/job-template.yaml#L128) and [2](https://github.com/thoth-station/init-job/blob/master/openshift/job-template.yaml#L143) which I'm deleting.

**Comment by fridex** [comment]
> > @bissenbay @fridex sorry for missing this PR.
> > I would suggest keeping the Tag, and using it in here
> > https://github.com/thoth-station/init-job/blob/67546dc7c0d482725e87b0d8c505f5c84c786455/openshift/job-template.yaml#L41
> > 
> > with us moving to ci/cd tools for managing image and deployment, maybe having custom tag would help.
> 
> @fridex @harshad16 Thanks, I did the change you asked. But, the thing I say redundant is `IMAGE_STREAM_TAG` parameter is written twice that's why I'm deleting one of them. The first is [1](https://github.com/thoth-station/init-job/blob/master/openshift/job-template.yaml#L128) and [2](https://github.com/thoth-station/init-job/blob/master/openshift/job-template.yaml#L143) which I'm deleting.

Ah, ok. So we also fixed a bug :+1:

**Pull request merged**
